baseURL = "https://KeeTub.github.io/BibleKim/"
languageCode = "ko-kr"
title = "Praxis Bible"
theme = "hugo-theme-stack"
copyright = "BibleKim"

[services]
    [services.googleAnalytics]
        id = ""

[params]
    mainSections = ["posts"]
    colorScheme = "auto" # ìë™ìœ¼ë¡œ ë‹¤í¬/ë¼ì´íŠ¸ ëª¨ë“œ ì¡°ì ˆ
    
    [params.sidebar]
        emoji = "ğŸ“–"
        subtitle = "í—¬ë¼ì–´ ì›ì „ ì—°êµ¬ì™€ ë¬µìƒ"
        avatar = "avatar.jpg"  # ë‚˜ì¤‘ì— í”„ë¡œí•„ ì‚¬ì§„ ë„£ì„ ì´ë¦„

    [params.footer]
        since = 2026